global:
 message: Welcome to order service dev environment !!
server:
 port: 8084
message: Hello from order dev !
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/springboot
  username: root
  password: manager@123
  driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate: 
   ddl-auto: update
   show-sql: true
